language: python

python:
    - 3.6
    - 3.8

services:
    - xvfb

script:
    - python setup.py install 
    - xvfb-run -a plotdigitizer -i ./figures/trimmed.png -p 0,0 -p 20,0 -p 0,1 \
      -l 22,295 -l 142,296 -l 23,215 \
      --plot

